@url = http://localhost:5010/sales-module 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjgzZDNjYi02ODkwLTQ4ZTgtOTM2Ni05ODA3NGM1MjQ4NTQiLCJ1bmlxdWVfbmFtZSI6IjU2ODNkM2NiLTY4OTAtNDhlOC05MzY2LTk4MDc0YzUyNDg1NCIsImp0aSI6IjdjNDc1YjJjLTE2N2YtNGYzMC05OTIwLWI0MjE4Mzc4MzdhZiIsImlhdCI6IjE2NDYxNjczNjE3OTYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsidXNlcnMiLCJpdGVtcyIsIml0ZW0tc2FsZSJdLCJuYmYiOjE2NDYxNjczNjEsImV4cCI6MTY0NjE3MDk2MSwiaXNzIjoiZWNvbW1lcmNlIn0.lHW9-1MTfthZkKiSr831hbfvxnMsWIgDi29b71ad6bY
@orderItemId = b22790a1-0281-4bec-9cf8-5c83c0b87379
@itemSaleId = 7ce20008-8f4b-4bdd-a06f-8f5edc8e2b4c
@orderId = c8b1357f-e25c-42c7-a174-4d3c674d676d
@customerId = 2482141f-e4e8-4efb-8750-44c45f332372
@paymentId = 67d2ec07-17b5-41f2-8f06-388debaf45e8

### API status
GET {{url}}

### Get order item
GET {{url}}/order-items/{{orderItemId}}
Authorization: Bearer {{accessToken}}

### Add order item
POST {{url}}/order-items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "itemSaleId": "{{itemSaleId}}"
}

### Delete order item
DELETE {{url}}/order-items/{{orderItemId}}
Authorization: Bearer {{accessToken}}

### Add order item
POST {{url}}/order-items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "itemSaleId": "{{itemSaleId}}"
}

### Get my orders
GET {{url}}/orders/me
Authorization: Bearer {{accessToken}}

### Get all order items in cart
GET {{url}}/cart/me
Authorization: Bearer {{accessToken}}


### Get order
GET {{url}}/orders/{{orderId}}
Authorization: Bearer {{accessToken}}

### Add order
POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "customerId": "{{customerId}}"
}

### Add position to order
PATCH {{url}}/orders/positions/add
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "orderId": "{{orderId}}",
    "itemSaleId": "{{itemSaleId}}"
}

### Delete position from order
PATCH {{url}}/orders/positions/delete
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "orderId": "{{orderId}}",
    "orderItemId": "{{orderItemId}}"
}

### Get my payments
GET {{url}}/payments/me
Authorization: Bearer {{accessToken}}

### Get payment
GET {{url}}/payments/{{paymentId}}
Authorization: Bearer {{accessToken}}

### Add payment
POST {{url}}/payments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "orderId": "{{orderId}}"
}

### Delete payment
DELETE {{url}}/payments/{{paymentId}}
Authorization: Bearer {{accessToken}}

### Delete order
DELETE {{url}}/orders/{{orderId}}
Authorization: Bearer {{accessToken}}