version: '3.8'
services:
  arangodb:
    image: arangodb
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=P4SSW0Rd!1
    ports:
      - 8529:8529
    volumes:
      - arangodb-data:/var/lib/arangodb3
    restart: always

volumes:
  arangodb-data:
