@url = http://localhost:5010/purchase-profiler-module 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNzBiNmRiOC1mNzdhLTRjZTctODMzZi05Nzc2MTdjZjE4NzMiLCJ1bmlxdWVfbmFtZSI6ImU3MGI2ZGI4LWY3N2EtNGNlNy04MzNmLTk3NzYxN2NmMTg3MyIsImp0aSI6IjNjODhiN2Y3LTU1NGQtNDdkZC1iZDE3LWFkMDMxNTk1N2VjOSIsImlhdCI6IjE3MzQzMDE5MTAyODYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbInVzZXJzIiwiaXRlbXMiLCJpdGVtLXNhbGUiLCJjdXJyZW5jaWVzIl0sIm5iZiI6MTczNDMwMTkxMCwiZXhwIjoxNzM0MzA1NTEwLCJpc3MiOiJlY29tbWVyY2UifQ.CZjxTjkHsGM5ewMBD3Io9yP2kChaO3IbHHJfvMnGzMc
@userId = e70b6db8-f77a-4ce7-833f-977617cf1873

###
GET {{url}}/recomendations/{{userId}}
Authorization: {{accessToken}}
