@url = http://localhost:5010/purchase-profiler-module 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNzBiNmRiOC1mNzdhLTRjZTctODMzZi05Nzc2MTdjZjE4NzMiLCJ1bmlxdWVfbmFtZSI6ImU3MGI2ZGI4LWY3N2EtNGNlNy04MzNmLTk3NzYxN2NmMTg3MyIsImp0aSI6ImQ4YjQ1NTRmLTY1YzgtNGMyOC05N2IyLTA0OWI3NmU3NjA0YiIsImlhdCI6IjE3MzYxMTEzMjUyNjkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbInVzZXJzIiwiaXRlbXMiLCJpdGVtLXNhbGUiLCJjdXJyZW5jaWVzIl0sIm5iZiI6MTczNjExMTMyNSwiZXhwIjoxNzM2MTE0OTI1LCJpc3MiOiJlY29tbWVyY2UifQ.y3cxkopdcd__w3bh4iVdcEuYzC-KVP2kKg2nHCPoX-0
@userId = e70b6db8-f77a-4ce7-833f-977617cf1873

###
GET {{url}}/recomendations
Authorization: Bearer {{accessToken}}
