@url = http://localhost:5010/currencies-module
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjgzZDNjYi02ODkwLTQ4ZTgtOTM2Ni05ODA3NGM1MjQ4NTQiLCJ1bmlxdWVfbmFtZSI6IjU2ODNkM2NiLTY4OTAtNDhlOC05MzY2LTk4MDc0YzUyNDg1NCIsImp0aSI6IjdiMjE2NzBhLWNkMjctNGM3MC04ODljLTY4OGU0Nzc0OGY0NiIsImlhdCI6IjE2NDQwODU4MTcyNzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOiJ1c2VycyIsIm5iZiI6MTY0NDA4NTgxNywiZXhwIjoxNjQ0MDg5NDE3LCJpc3MiOiJlY29tbWVyY2UifQ.cHN8H02JJLaMzD1vMaVdrGMtHuH44ZGK4TcWSvT8VMI
@currencyId = bd5252e6-475d-4120-8447-c8ec09280d54
@date = 2022-02-03

### 
GET {{url}}

### Get currencies
GET {{url}}/currencies

### Get currency
GET {{url}}/currencies/{{currencyId}}

### Add currency
POST {{url}}/currencies
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "code": "EUR",
    "description": "euro"
}

### Update currency
PUT {{url}}/currencies/{{currencyId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "code": "EUR",
    "description": "euro waluta Europrejska"
}

### Delete currency
DELETE {{url}}/currencies/{{currencyId}}
Authorization: Bearer {{accessToken}}

### Get latest rate for currency
GET {{url}}/currency-rates/{{currencyId}}

### Get rate for currency and date
GET {{url}}/currency-rates/?currencyId={{currencyId}}&date={{date}}