@url = http://localhost:5000/users-module 
@email = test@gmail.com
@password = password
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjgzZDNjYi02ODkwLTQ4ZTgtOTM2Ni05ODA3NGM1MjQ4NTQiLCJ1bmlxdWVfbmFtZSI6IjU2ODNkM2NiLTY4OTAtNDhlOC05MzY2LTk4MDc0YzUyNDg1NCIsImp0aSI6Ijg0ZmFlZThhLWVhYmQtNDkxYS1hYTcwLWEzMjRiM2FiZjE0YiIsImlhdCI6IjE2NDU1NjMzOTgwNjkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOiJ1c2VycyIsIm5iZiI6MTY0NTU2MzM5OCwiZXhwIjoxNjQ1NTY2OTk4LCJpc3MiOiJlY29tbWVyY2UifQ.k1VO52rgY2DymC4dix4RRC3smKAAM90ZJ532I0lsu_k

### 
GET {{url}}

### Get account
GET {{url}}/account
Authorization: Bearer {{accessToken}}

### Register
POST {{url}}/account/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}", 
    "role": "{{role}}",
    "claims":{
        "permissions": ["users"]
    }
}

### Login
POST {{url}}/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}