@url = http://localhost:5010/users-module 
@email = test@gmail.com
@password = password
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjgzZDNjYi02ODkwLTQ4ZTgtOTM2Ni05ODA3NGM1MjQ4NTQiLCJ1bmlxdWVfbmFtZSI6IjU2ODNkM2NiLTY4OTAtNDhlOC05MzY2LTk4MDc0YzUyNDg1NCIsImp0aSI6IjMwOWQ1NWVjLWNkNGUtNGZjZS04NDEyLWVhZmIyMDMxYWZmNyIsImlhdCI6IjE2NTE0ODY4MDE5NzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbInVzZXJzIiwiaXRlbXMiLCJpdGVtLXNhbGUiLCJjdXJyZW5jaWVzIl0sIm5iZiI6MTY1MTQ4NjgwMSwiZXhwIjoxNjUxNDkwNDAxLCJpc3MiOiJlY29tbWVyY2UifQ.L75G4ALHSDrdDHWqzxuCJs_QdINCD61AyYSX7GuCnAw
@searchEmail = t
@userId = 434aeb4a-1de9-4d64-a662-723408650823

### 
GET {{url}}

### Get account
GET {{url}}/account
Authorization: Bearer {{accessToken}}

### Register
POST {{url}}/account/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}", 
    "role": "{{role}}",
    "claims":{
        "permissions": ["users"]
    }
}

### Login
POST {{url}}/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
GET {{url}}/accounts
Authorization: Bearer {{accessToken}}

###
GET {{url}}/accounts/search?email={{searchEmail}}
Authorization: Bearer {{accessToken}}

###
PATCH {{url}}/accounts/{{userId}}/active
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "{{userId}}",
    "active": false
}

###
GET {{url}}/accounts
Authorization: Bearer {{accessToken}}

###
PATCH {{url}}/accounts/{{userId}}/active
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "{{userId}}",
    "active": true
}

###
GET {{url}}/accounts
Authorization: Bearer {{accessToken}}