@url = http://localhost:5010/items-module 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjgzZDNjYi02ODkwLTQ4ZTgtOTM2Ni05ODA3NGM1MjQ4NTQiLCJ1bmlxdWVfbmFtZSI6IjU2ODNkM2NiLTY4OTAtNDhlOC05MzY2LTk4MDc0YzUyNDg1NCIsImp0aSI6IjE1NTFiNzg5LWQxZjMtNDM1ZS1iODk5LTBkNmFkOTc1NTJmYiIsImlhdCI6IjE2NDU4Nzc1MjI2NTgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsidXNlcnMiLCJpdGVtcyIsIml0ZW0tc2FsZSJdLCJuYmYiOjE2NDU4Nzc1MjIsImV4cCI6MTY0NTg4MTEyMiwiaXNzIjoiZWNvbW1lcmNlIn0.WxQQ7c_xJd-fnw8uDyhg0-gnwBH0Ro06woRjt1BeCLU
@itemId = a5cc05ee-f533-49d2-a095-132d5dfc6241
@brandId = 251516e0-03af-4688-b388-c427e2200a81
@typeId = 702e7fa1-1ea0-41ec-8fce-e968e7dbf5be
@imageId = f21cef1e-456a-4ccc-afb3-c4175fa9ccf4
@itemSaleId = 7ce20008-8f4b-4bdd-a06f-8f5edc8e2b4c
@itemCost = 5000
@date = 2022-02-03
@currencyCode = PLN

### 
GET {{url}}

### Get items
GET {{url}}/items

### Get item
GET {{url}}/items/{{itemId}}

### Add brand
POST {{url}}/brands
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Samsung"
}

### Get brands
GET {{url}}/brands

### Get brand
GET {{url}}/brands/{{brandId}}

### Add type
POST {{url}}/types
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Electric"
}

### Get types
GET {{url}}/types

### Get type
GET {{url}}/types/{{typeId}}

### Add image
POST {{url}}/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Samsung.jpg"
Content-Type: image/jpeg

< ./Samsung.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW


### Get image
GET {{url}}/images/{{imageId}}

### Add item
POST {{url}}/items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "itemName": "Samsung S22",
    "brandId": "{{brandId}}",
    "typeId": "{{typeId}}",
    "tags": [ "samsung", "S22" ], 
    "imagesUrl": [
        {
            "url": "https://ithardware.pl/admin/ckeditor/filemanager/userfiles/DanielGorecki/2022/Stycze%C5%84/galaxy_s22.jpg?time=1643274614771",
            "mainImage": true
        },
        {
            "url": "https://files.mgsm.pl//news/15953/samsung-galaxy-s22-ultra-large.jpg",
            "mainImage": false
        },
        {
            "url": "https://i.wpimg.pl/O/730x0/m.komorkomania.pl/obraz-2021-09-27-130821-afe03036.png",
            "mainImage": false
        }
    ]
}

### Update item
PUT {{url}}/items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "itemId": "{{itemId}}",
    "itemName": "Samsung S22",
    "description": "Wyświetlacz \"6.8\", 3080 x 1440px, Dynamic AMOLED 2X; Pamięć wbudowana [GB] 128; Pamięć RAM 8 GB",
    "brandId": "{{brandId}}",
    "typeId": "{{typeId}}",
    "tags": [ "Samsung", "S22" ], 
    "imagesUrl": [
        {
            "url": "https://ithardware.pl/admin/ckeditor/filemanager/userfiles/DanielGorecki/2022/Stycze%C5%84/galaxy_s22.jpg?time=1643274614771",
            "mainImage": true
        },
        {
            "url": "https://files.mgsm.pl//news/15953/samsung-galaxy-s22-ultra-large.jpg",
            "mainImage": false
        },
        {
            "url": "https://i.wpimg.pl/O/730x0/m.komorkomania.pl/obraz-2021-09-27-130821-afe03036.png",
            "mainImage": false
        }
    ]
}

### Get items sale
GET {{url}}/item-sales

### Get item sale
GET {{url}}/item-sales/{{itemSaleId}}

### Add item sale
POST {{url}}/item-sales
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "itemId": "{{itemId}}",
    "itemCost": "{{itemCost}}",
    "currencyCode": "{{currencyCode}}"
}

### Update item sale
PUT {{url}}/item-sales
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "itemSaleId": "{{itemSaleId}}",
    "itemCost": "{{itemCost}}",
    "currencyCode": "{{currencyCode}}"
}

### DELETE item sale
DELETE {{url}}/item-sales/{{itemSaleId}}
Authorization: Bearer {{accessToken}}

### DELETE item
DELETE {{url}}/items/{{itemId}}
Authorization: Bearer {{accessToken}}

### Update brand
PUT {{url}}/brands
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "brandId": "{{brandId}}",
    "name": ""
}

### DELETE brand
DELETE {{url}}/brands/{{brandId}}
Authorization: Bearer {{accessToken}}

### Update type
PUT {{url}}/types
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "brandId": "{{typeId}}",
    "name": ""
}

### DELETE brand
DELETE {{url}}/types/{{typeId}}
Authorization: Bearer {{accessToken}}

### GET all items not put up for sale
GET {{url}}/items/not-put-up-for-sale