@url = http://localhost:5000/currencies-module
@currencyId = bd5252e6-475d-4120-8447-c8ec09280d54
@date = 2022-02-03

### 
GET {{url}}

### Get currencies
GET {{url}}/currencies

### Get currency
GET {{url}}/currencies/{{currencyId}}

### Add currency
POST {{url}}/currencies
Content-Type: application/json

{
    "code": "EUR",
    "description": "euro"
}

### Update currency
PUT {{url}}/currencies/{{currencyId}}
Content-Type: application/json

{
    "code": "EUR",
    "description": "euro waluta Europrejska"
}

### Delete currency
DELETE {{url}}/currencies/{{currencyId}}

### Get latest rate for currency
GET {{url}}/currency-rates/{{currencyId}}

### Get rate for currency and date
GET {{url}}/currency-rates/?currencyId={{currencyId}}&date={{date}}